### ISSUE TITLE
Reverse Complement is failing with Biopython incompatability issues on v 5.5.0 and bio 1.81

### ISSUE THREAD

**Issue by zslastman** [pydna-group/pydna#349]
I am still getting this error:

In [2]: sys.version
Out[2]: '3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]'

In [3]: import Bio

In [4]: Bio.__version__
Out[4]: '1.81'

In [5]: import pydna.dseqrecord

In [6]: import pydna

In [7]: pydna.__version__
Out[7]: '5.5.0'

In [10]: pydna.dseqrecord.Dseqrecord('aaa').rc()
------------------------------------------------------------
TypeError                  Traceback (most recent call last)
Cell In[10], line 1
----> 1 pydna.dseqrecord.Dseqrecord('aaa').rc()

File ~/miniconda3/lib/python3.11/site-packages/pydna/dseqrecord.py:941, in Dseqrecord.reverse_complement(self)
    917 def reverse_complement(self):
    918     """Reverse complement.
    919 
    920     Examples
   (...)
    939 
    940     """
--> 941     answer = type(self)(super().reverse_complement())
    942     answer.name = "{}_rc".format(self.name[:13])
    943     answer.description = self.description + "_rc"

File ~/miniconda3/lib/python3.11/site-packages/pydna/seqrecord.py:144, in SeqRecord.reverse_complement(self, *args, **kwargs)
    142 def reverse_complement(self, *args, **kwargs):
    143     """Return the reverse complement of the sequence."""
--> 144     answer = super().reverse_complement(*args, **kwargs)
    145     answer = type(self).from_Bio_SeqRecord(answer)
    146     return answer

File ~/miniconda3/lib/python3.11/site-packages/Bio/SeqRecord.py:1238, in SeqRecord.reverse_complement(self, id, name, description, features, annotations, letter_annotations, dbxrefs)
   1233     seq = self.seq.reverse_complement_rna(
   1234         inplace=False
   1235     )  # TODO: remove inplace=False
   1236 else:
   1237     # Default to DNA)
-> 1238     seq = self.seq.reverse_complement(
   1239         inplace=False
   1240     )  # TODO: remove inplace=False
   1241 if isinstance(self.seq, MutableSeq):
   1242     seq = Seq(seq)

TypeError: Dseq.reverse_complement() got an unexpected keyword argument 'inplace'

**Comment by manulera** [comment]
Hi @zslastman thanks for reporting this bug. Indeed, there is a problem in our project requirements and pydna 5.5 no longer supports biopython 1.81.

As far as i can tell, reverse complement works with 1.82, but anyway I would recommend installing biopython 1.85, which is the version ran in our ci/cd that passes all tests.

We have a meeting today with the team, so we will discuss whether we should just pin the latest version. Do you have some feedback on this? (would it be a problem for you to pin 1.85?)

The pydna meeting is open, by the way. Feel free to join at 15:00 UK time today at the below teams link, we are always happy to hear from pydna's users.

https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDQ1ODVlZTYtYmE2OS00ZWEyLTgzYjEtNjllZGNhZDNiODE2%40thread.v2/0?context=%7b%22Tid%22%3a%221faf88fe-a998-4c5b-93c9-210a11d9a5c2%22%2c%22Oid%22%3a%22e1394e78-cf0f-492d-9394-b06f66175536%22%7d
